//
//      Copyright (c) Fusion Processing Ltd 2014-2020
//      All rights reserved.
//

#pragma once

enum TcpErrorCode
{
    TCPERR_NO_ERROR = 0,
    TCPERR_INVALID_STATE,
    TCPERR_FAILED_MALLOC,
    TCPERR_OPENING_SOCKET,
    TCPERR_SETTING_SOCKET_OPT,
    TCPERR_NOT_CONNECTED,
    TCPERR_ALREADY_CONNECTED,
    TCPERR_ACCEPTING_CONNECTION,
    TCPERR_WRITING_TO_CLIENT,
    TCPERR_WRITING_TO_SERVER,
    TCPERR_CONNECTION_LOST
};
