//
//      Copyright (c) Fusion Processing Ltd 2020
//      All rights reserved.
//

#pragma once

enum ErrorCode
{
    ERR_NO_ERROR = 0,

    // Internal errors returned by functions
    ERR_INVALID_STATE,
    ERR_INVALID_PARAMETER,
    ERR_FAILED_MALLOC,
    ERR_FAILED_FILE_OPEN,
    ERR_FAILED_OPERATION,

    // Internal warnings
    ERR_SLOW_ITERATION,
    ERR_UNEXPECTED_SIZE,
    ERR_UNRECOGNISED_TAG,

    //TODO RIFF errors to be removed
    ERR_INVALID_TAG,
    ERR_INVALID_DATA,
    ERR_SOCKET_ERROR,
    ERR_CONNECTION_LOST,

    // Config errors
    ERR_CONFIG_LINE_TOO_LONG,
    ERR_CONFIG_FILE_TOO_LONG,
    ERR_CONFIG_KEY_NOT_FOUND,
    ERR_CONFIG_VALUE_NOT_INTEGER,
    ERR_CONFIG_VALUE_NOT_FLOAT,
    ERR_CONFIG_RECURSE_LIMIT,

    // Function errors
    ERR_CAN_TIMEOUT,
    ERR_ODOMETRY_TIMEOUT,
    ERR_STEER_SENSOR_FAULT,
    ERR_STEER_MOTOR_FAULT,
    ERR_GNSS_RECEIVE,
    ERR_MEMS_READ,
    ERR_LC_TURNING_OFFSET,
    ERR_LC_WHEEL_DIFFERENCE,
    ERR_LC_LARGE_DISTANCE,
    ERR_LC_INVALID_HEADING,
    ERR_MD_PARSER_ERROR,
    ERR_MD_MISSING_ATTRIBUTE,
    ERR_MD_INVALID_MAP,
    ERR_SP_FAILED_TO_FIND_CLOSEST_SEGMENT,
    ERR_SP_TOO_FAR_FROM_MAP,
    ERR_SP_NO_ROUTE,
    ERR_TP_SPLINE_POINT,
    ERR_WLD_INPUTS,
    ERR_WLD_TIMEOUT,
    ERR_WLD_MISSING_SENSOR,
    ERR_WLD_NO_SENSOR,
    ERR_WLD_DATA_SYNC,
};

